{{- if .Values.airflow.enabled }}
{{- if .Values.airflow.dags.gitSync.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
data:
  GIT_SYNC_USERNAME: {{ .Values.gitSync.username | b64enc | quote}}
  GIT_SYNC_PASSWORD: {{ .Values.gitSync.password | b64enc | quote}}

{{end}}
{{end}}